# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target "DotaDog" do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.7.5'
pod 'FMDB', '~> 2.6.2'
pod 'Masonry' 
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'ReactiveCocoa', '~> 4.1.0'
end